const colors = {
  light: {
    text: "#1A0533",
    tint: "#7C3AED",
    background: "#FFFFFF",
    foreground: "#1A0533",
    card: "#F5F0FF",
    cardForeground: "#1A0533",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#5B21B6",
    muted: "#F3F0FF",
    mutedForeground: "#8B7AA0",
    accent: "#A78BFA",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5DEFF",
    input: "#E8E0FF",
    success: "#10B981",
    successLight: "#D1FAE5",
    warning: "#F59E0B",
    warningLight: "#FEF3C7",
    info: "#3B82F6",
    infoLight: "#DBEAFE",
  },
  dark: {
    text: "#F0EAFF",
    tint: "#A78BFA",
    background: "#0D0818",
    foreground: "#F0EAFF",
    card: "#1A1030",
    cardForeground: "#F0EAFF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#2A1A4A",
    secondaryForeground: "#C4B5FD",
    muted: "#160E28",
    mutedForeground: "#9B8CB0",
    accent: "#7C3AED",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D1F4A",
    input: "#2D1F4A",
    success: "#10B981",
    successLight: "#052E1C",
    warning: "#F59E0B",
    warningLight: "#2D1F00",
    info: "#3B82F6",
    infoLight: "#0F1E3A",
  },
  radius: 12,
};

export default colors;
